apiVersion: v1
kind: Service
metadata:
  name: {{ include "static-log-analysis.fullname" . }}
  labels:
    {{- include "static-log-analysis.labels" . | nindent 4 }}
    app.kubernetes.io/component: analysis
spec:
  type: ClusterIP
  selector:
    {{- include "static-log-analysis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: analysis
  ports:
    - name: otlp-grpc
      port: 4317
      targetPort: otlp-grpc
    - name: otlp-http
      port: 4318
      targetPort: otlp-http
    - name: admin
      port: 9464
      targetPort: admin

