apiVersion: v1
kind: Service
metadata:
  name: {{ include "static-log-analysis.fullname" . }}-outbox
  labels:
    {{- include "static-log-analysis.labels" . | nindent 4 }}
    app.kubernetes.io/component: outbox
spec:
  type: ClusterIP
  selector:
    {{- include "static-log-analysis.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: outbox
  ports:
    - name: admin
      port: 9464
      targetPort: admin

