#!/bin/sh
set -eu

usage() {
  echo "usage: $0 COMPOSE_SERVICE OTEL_SERVICE_NAME DEPLOYMENT_ENVIRONMENT" >&2
  exit 2
}

[ "$#" -eq 3 ] || usage
compose_service=$1
otel_service=$2
deployment_environment=$3

for value in "$compose_service" "$otel_service" "$deployment_environment"; do
  case "$value" in
    ""|*[!A-Za-z0-9._-]*)
      echo "service and environment values may contain only letters, digits, dot, underscore, and hyphen" >&2
      exit 2
      ;;
  esac
done

cat <<EOF
# Generated by static-log-analysis/scripts/render-compose-integration.sh.
# Add this file after the repository's normal Compose file.
services:
  ${compose_service}:
    environment:
      OTEL_LOGS_EXPORTER: otlp
      OTEL_EXPORTER_OTLP_ENDPOINT: http://static-log-analysis-collector:4318
      OTEL_EXPORTER_OTLP_PROTOCOL: http/protobuf
      OTEL_SERVICE_NAME: ${otel_service}
      OTEL_RESOURCE_ATTRIBUTES: deployment.environment.name=${deployment_environment}
    networks:
      - default
      - static-log-analysis-ingress

networks:
  static-log-analysis-ingress:
    external: true
    name: \${SLA_INGRESS_NETWORK:-static-log-analysis-ingress}
EOF
